apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: workspace
spec:
  components:
    - name: workspace
      type: workspace
      properties:
        workloadClusters:
        - name: '*'
          namespaces:
          - name: '*'