apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: virtualgateway
spec:
  components:
    - name: virtualgateway
      type: virtualgateway
      properties:
        workloads:
          - selector:
              labels:
                istio: ingressgateway
              cluster: cluster1
              namespace: istio-gateways
        listeners:
          - http: {}
            port:
              number: 80
            allowedRouteTables:
              - host: '*'
                selector:
                  workspace: all