apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: gatewaylifecyclemanager
spec:
  components:
    - name: gatewaylifecyclemanager
      type: gatewaylifecyclemanager
      properties: