apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: gatewaylifecyclemanager
  namespace: vela-system
spec:
  schematic:
    cue:
      template: "output: {\n\tapiVersion: \"admin.gloo.solo.io/v2\"\n\tkind:       \"GatewayLifecycleManager\"\n\tmetadata:
        {\n\t\tname:      context.name\n\t\tnamespace: \"gloo-mesh\"\n\t}\n\tspec:
        installations: parameter.installations\n}\noutputs: {}\nparameter: installations:
        [...{\n\tclusters: [...{name: string, activeGateway: *false | bool}]\n\tgatewayRevision:
        \     string\n\tcontrolPlaneRevision: string\n\tistioOperatorSpec: {...}\n}]\n"
  workload:
    definition:
      apiVersion: admin.gloo.solo.io/v2
      kind: GatewayLifecycleManager
    type: gatewaylifecyclemanagers.admin.gloo.solo.io
