apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: nginx 
  namespace: default
spec:
  components:
    - name: nginx-basic
      type: webservice
      properties:
        image: nginx
      traits: 
      - type: service-mesh 
        properties:
          enabled: true
  policies:
    - name: all
      type: topology
      properties:
        clusters: ["cluster1", "cluster2"]
