apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: virtualdestination
spec:
  components:
    - name: virtualdestination
      type: virtualdestination
      properties:
        hosts:
        - checkout.backend-apis-team.solo-io.mesh
        services:
        - labels:
            app: checkoutservice
        ports:
        - number: 80
          protocol: GRPC
          targetPort:
            name: grpc