apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: routetable
spec:
  components:
    - name: routetable
      type: routetable
      properties:
        hosts:
          - '*'
        virtualGateways:
          - name: north-south-gw
            namespace: gloo-mesh
            cluster: mgmt
        workloadSelectors: []
        http:
          - name: frontend
            forwardTo:
              destinations:
                - ref:
                    name: frontend
                    namespace: web-ui
                    cluster: cluster1
                  port:
                    number: 80