apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: workspacesettings
  namespace: vela-system
spec:
  schematic:
    cue:
      template: "output: {\n\tapiVersion: \"admin.gloo.solo.io/v2\"\n\tkind:       \"WorkspaceSettings\"\n\tmetadata:
        {\n\t\tname:      context.name\n\t\tnamespace: context.namespace\n\t}\n\tspec:
        {\n\t\texportTo:   parameter.exportTo\n\t\timportFrom: parameter.importFrom\n\t\toptions:
        \   parameter.options\n\t}\n}\noutputs: {}\nparameter: {\n\texportTo:         *[]
        | [...]\n\timportFrom:       *[] | [...]\n\teastWestGateways: *[] | [...]\n\toptions:
        federation: enabled:               *false | bool\n\toptions: serviceIsolation:
        enabled:         *true | bool\n\toptions: serviceIsolation: trimProxyConfig:
        *true | bool\n}\n"
  workload:
    definition:
      apiVersion: admin.gloo.solo.io/v2
      kind: WorkspaceSettings
    type: workspacesettings.admin.gloo.solo.io